export const CHECKOUT_WELCOME_COPY = {
  eyebrow: 'Paso V',
  legend: 'Vuestra noche os espera',
  subtitle: 'Un último paso para confirmar y dejar todo sellado.',
  footnote: 'Discreción absoluta · Sin juicios',
} as const

export const STEP5_CHECKOUT_COPY = {
  title: 'Confirma tu noche',
  subtitle: 'Revisad el resumen, descubrid vuestra esencia y completad el pago con total tranquilidad.',
  summaryHeading: 'Tu noche',
  paymentHeading: 'Abonar tu noche',
  paymentHint: 'Datos del titular y tarjeta. Simulación segura en este prototipo.',
  holderNameLabel: 'Nombre real del titular',
  holderNameHint: 'Puede ser distinto del apodo que usaréis en la sala.',
  holderNamePlaceholder: 'Nombre y apellidos, como en el documento',
  emailLabel: 'Correo electrónico',
  emailHint: 'Enviaremos la confirmación y el acceso a vuestra noche.',
  emailPlaceholder: 'tu@correo.com',
  documentTypeLabel: 'Documento',
  documentNumberLabel: 'Número de documento',
  documentNumberPlaceholder: '12345678Z',
  cardNumberLabel: 'Número de tarjeta',
  expiryLabel: 'Caducidad',
  cvcLabel: 'CVC',
  simulationNote: 'Pago simulado: no se realiza ningún cargo real.',
  successTitle: 'Reserva confirmada',
  successSubtitle: 'Vuestra noche queda sellada. Guardad el código de confirmación.',
  confirmationCodeLabel: 'Código de confirmación',
  tocadorHeading: 'El Tocador',
  tocadorEmpty: 'Sin kits · La noche tal cual',
  statementLabel: 'En tu extracto aparecerá como',
  statementValue: 'Ocio y Eventos SL',
  lineBase: 'Experiencia',
  lineTocador: 'Kits del tocador',
  lineTotal: 'Total',
  discountLabel: 'Código de descuento',
  discountPlaceholder: 'Introduce código',
  scrollToPay: 'Ir al pago',
  confirmNight: 'Confirmar mi noche',
  processing: 'Procesando…',
  preparingPayment: 'Preparando el pago…',
  demoHint: 'Modo demo: podéis confirmar la noche y continuar al panel sin cobro real.',
  trustCancel: 'Cancelación libre 48h antes',
  trustPrivacy: 'Discreción absoluta',
  trustSupport: 'Siempre hay alguien para vosotros',
} as const
